apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app
  namespace: argocd
spec:
  destination:
    namespace: hello-world
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/Siluvai1997/argocd-helm-helloworld-bootstrap-openshift.git'
    targetRevision: HEAD
    path: helm/hello-world
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
