apiVersion: v1
kind: LimitRange
metadata:
  name: hello-world-limits
  namespace: hello-world
  annotations:
    managed-by: "ArgoCD"
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      type: Container
