apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-pvc
  namespace: hello-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hello-world-storageclass
