apiVersion: v1
kind: ResourceQuota
metadata:
  name: hello-world-quota
  namespace: hello-world
  annotations:
    managed-by: "ArgoCD"
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"
