apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hello-world-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
