apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
  wildcardPolicy: None
